version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ksd-bot
    volumes: 
      - /opt/homebrew/bin/postgres
    ports:
      - '5432:5432'
